name: Merge Sort Test
on: [push]
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0-rc.1'
      - name: set up pylint badge
        uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: rand.py
          python-version: '3.13.0-rc.1' 
      - name: Static Analysis
        run: |
          pip install pytest
          pip install pylint
          pip install bandit
          pip install git+https://github.com/blengerich/pylint-badge
          pylint **/*.py
          bandit --exclude="test_*.py" . 
      - name: Set Up Coverage
        run: |
          pip install genbadge[coverage]
          pip install coverage
      - name: Test with pytest
        run: |
          pip install pytest-cov coveralls
          coverage run -m pytest test_hw2.py
          coveralls --service=github-actions
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --exit-code --recursive --in-place --aggressive .
      
      - name: Update README.md with latest run
        run: |
          sed -i "s|(https://github.com/CSC510-GROUP-40/Homework_2/actions/runs.*)|(https://github.com/CSC510-GROUP-40/Homework_2/actions/runs/${{ github.run_id }})|" README.md

      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Automated autopep8 fixes and Update README.md with the latest run ID"
          git push
      
          