name: Merge Sort Test
on: 
  push:
    branches:
      - lawrence/feature/pylintbadge 
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0-rc.1'
      - name: set up pylint badge
        uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: rand.py
          python-version: '3.13.0-rc.1' 
      - name: Static Analysis
        run: |
          pip install pytest
          pip install pylint
          pip install bandit
          pip install git+https://github.com/blengerich/pylint-badge
          pylint **/*.py
          bandit --exclude="test_*.py" . 
      - name: Set Up Coverage
        run: |
          pip install genbadge[coverage]
          pip install coverage
      - name: Test with pytest
        run: |
          pip install pytest-cov coveralls
          coverage run -m pytest test_hw2.py
          coveralls --service=github-actions
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          